### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by vorburger** [daniel-wells/beancount_checkclosed#1]
@daniel-wells thanks for making this plugin available! I tried it out but it doesn't work, at least for me:

```
$ bean-check my.beancount
<load>:0:       Error applying plugin "beancount_checkclosed.check_closed": Traceback (most recent call last):
    File "/home/vorburger/.local/lib/python3.11/site-packages/beancount/loader.py", line 602, in run_transformations
      entries, plugin_errors = callback(entries, options_map, *args)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/vorburger/.local/lib/python3.11/site-packages/beancount_checkclosed/check_closed.py", line 42, in check_closed
      for currency in entry.currencies:
  TypeError: 'NoneType' object is not iterable
```

**Comment by daniel-wells** [comment]
Hi, thanks for raising this issue.
The problem was that the plugin was assuming that you had explicitly listed all the currencies in the "open" entries for each account.
I've updated (5abc380) the plugin to infer the currencies used for the accounts if they're not explicitly listed in the open entries.
So hopefully the latest version should work for you if I've correctly inferred the reason for your error.

**Comment by vorburger** [comment]
Works great! Thanks a lot for the super fast fix.
